version: '3.9'

services:
  teable:
    image: ghcr.io/teableio/teable:latest
    deploy:
      replicas: 2
    restart: always
    expose:
      - "3001"
    env_file:
      - .env
    environment:
      - TZ=${TIMEZONE}
      - NEXT_ENV_IMAGES_ALL_REMOTE=true
      - LOG_LEVEL=debug
    volumes:
      - ${I18NEXT_DEFAULT_CONFIG_PATH}
    networks:
      - coolify
      - teable-cluster
    depends_on:
      teable-db-migrate:
        condition: service_completed_successfully
      teable-cache:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3001/health']
      start_period: 5s
      interval: 5s
      timeout: 3s
      retries: 3
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teable.rule=Host(`teable.se`)"
      - "traefik.http.routers.teable.entrypoints=http,https"
      - "traefik.http.services.teable.loadbalancer.server.port=3001"
      - "traefik.http.routers.teable.tls=true"
      - "traefik.http.routers.teable.tls.certresolver=letsencrypt"

  teable-db:
    image: postgres:15.4
    restart: always
    expose:
      - '5432'
    volumes:
      - teable-db:/var/lib/postgresql/data:rw
    environment:
      - TZ=${TIMEZONE}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - teable-cluster
    healthcheck:
      test: ['CMD-SHELL', "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 10s
      timeout: 3s
      retries: 3

  teable-db-migrate:
    image: ghcr.io/teableio/teable-db-migrate:latest
    environment:
      - TZ=${TIMEZONE}
      - PRISMA_DATABASE_URL=${PRISMA_DATABASE_URL}
    networks:
      - teable-cluster
    depends_on:
      teable-db:
        condition: service_healthy

  teable-cache:
    image: redis:7.2.4
    restart: always
    expose:
      - '6379'
    volumes:
      - teable-cache:/data:rw
    networks:
      - teable-cluster
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3

  teable-storage:
    image: minio/minio:RELEASE.2024-02-17T01-15-57Z
    expose:
      - '9000'
      - '9001'
    environment:
      - MINIO_SERVER_URL=${MINIO_SERVER_URL}
      - MINIO_BROWSER_REDIRECT_URL=${MINIO_BROWSER_REDIRECT_URL}
      - MINIO_ROOT_USER=${MINIO_ACCESS_KEY}
      - MINIO_ROOT_PASSWORD=${MINIO_SECRET_KEY}
    volumes:
      - teable-storage:/data:rw
    networks:
      - teable-cluster
    command: server /data --console-address ":9001"

  createbuckets:
    image: minio/mc
    networks:
      - teable-cluster
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set teable-storage http://teable-storage:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY};
      /usr/bin/mc mb teable-storage/public;
      /usr/bin/mc anonymous set public teable-storage/public;
      /usr/bin/mc mb teable-storage/private;
      exit 0;
      "
    depends_on:
      teable-storage:
        condition: service_started

  teable-gateway:
    image: openresty/openresty:1.25.3.1-2-bookworm-fat
    restart: unless-stopped
    expose:
      - '80'
    volumes:
      - './gateway/conf.d:/etc/nginx/conf.d'
    networks:
      - teable-cluster
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost/healthcheck']
      interval: 10s
      timeout: 3s
      retries: 3
    depends_on:
      teable:
        condition: service_started
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.teable-gateway.rule=Host(`teable.se`) && PathPrefix(`/api`, `/socket`)"
      - "traefik.http.routers.teable-gateway.entrypoints=http,https"
      - "traefik.http.services.teable-gateway.loadbalancer.server.port=80"
      - "traefik.http.routers.teable-gateway.tls=true"
      - "traefik.http.routers.teable-gateway.tls.certresolver=letsencrypt"

networks:
  coolify:
    external: true
  teable-cluster:
    name: teable-cluster-network
    driver: bridge

volumes:
  teable-db: {}
  teable-cache: {}
  teable-storage: {}